version: "3"
x-env: &env
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: outcome_prediction
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    API_PORT: 8000

services:
  postgres:
    image: postgres
    container_name: postgres-container
    <<: *env

    ports:
      - "5432:5432"

  transformation:
    build:
      context: ./src/transformation/approach_1
      dockerfile: Dockerfile
    container_name: transformation-container
    <<: *env

    depends_on:
      - postgres

  expose-api:
    build:
      context: ./src/expose_api
      dockerfile: Dockerfile
    container_name: expose-api-container
    <<: *env

    ports:
      - "8000:8000"
    depends_on:
      - transformation
