version: "3"
services:
  expose-api:
    build:
      context: ./src/expose_api
      dockerfile: Dockerfile
    container_name: expose-api-container
    ports:
      - "8000:8000"
    depends_on:
      - transformation
    command: sh -c "sleep 80 && uvicorn api:api --host 0.0.0.0 --port 8000"
